[project]
name = "smol-agents-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.0.2",
    "smolagents[litellm,mcp,toolkit,transformers]>=1.22.0",
]
